stages:
    - build
    - test


build:
    stage:  build
    script:
        - pybot -d Results --reporttitle "NOMBRE PARA EL REPORTE" --logtitle "NOMBRE PARA EL LOG" Lectulandia.robot

test:
    stage: test
    script:
        - cat Results/log.html
