#services:
    #-docker

stages:
    - build
    - test

build:
    stage:  build
    script:
        - echo  "Building"
        - mkdir build
        - touch build/123.txt

test:
    stage: test
    script:
        - echo  "Testing"
        - test -f "build/123.txt"
