stages:
    - build_image
    - test_robot

build_image:
  image: docker:git
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/ddavilam/prueba-de-jenkins .
    - docker push registry.gitlab.com/ddavilam/prueba-de-jenkins:latest
  only:
    - master

test_robot:
    image: registry.gitlab.com/ddavilam/prueba-de-jenkins:latest

    script:
        -
