build_image:
  image: registry.gitlab.com/ddavilam/prueba-de-jenkins:latest
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/jamkit/robot-framework .
    - docker push registry.gitlab.com/jamkit/robot-framework:latest
  only:
    - master
